includes/pomo.php

I have used conditionally `DateTimeImmutable` Class if WP >= 5.3, in later released we can remove the conditions, please let me know in case I should change something in the code for issue #5 
References 
https://make.wordpress.org/core/2019/09/23/date-time-improvements-wp-5-3/
https://www.php.net/manual/en/class.datetimeimmutable.php

Recommended date time functions

---

includes/post.php

Register _locale and _original_post post metas.

---

includes/functions.php

Add the short_name option to bogo_available_languages().

---

bogo.php

Nothing refers to this cookie now.
Fixes #24

Don't set cookies

---

admin/admin.php
admin/includes/language-packs.php
admin/includes/nav-menu.php
admin/includes/post.php
admin/includes/terms-translation.php
admin/includes/upgrade.php
admin/includes/user.php
admin/includes/widgets.php
bogo.php
includes/block-editor.php
includes/capabilities.php
includes/functions.php
includes/language-switcher.php
includes/link-template.php
includes/nav-menu.php
includes/pomo.php
includes/post.php
includes/query.php
includes/rest-api.php
includes/rewrite.php
includes/user.php
includes/widgets.php

Refactor code based on the coding standard

---

admin/includes/post.php

Remove unused variables

---

includes/post.php

Actually it can have any data as long as it's unique.
See #17

Don't premise that `_original_post` has post ID

---

includes/post.php

Set _original_post to post GUID

---

includes/query.php

_original_post is GUID

---

includes/post.php

Use static variables for function output

---

includes/post.php

Use pre_wp_unique_post_slug

---

admin/admin.php
admin/includes/language-packs.php

I18N: Improve translator comments.

---

includes/language-switcher.php

Wrap each language name with span

---

includes/functions.php

Introduce bogo_format_atts()

---

includes/language-switcher.php

Improve language switcher

---

includes/functions.php

Exclude en_US if inactive

---

readme.txt

Add Privacy Notices to the plugin page

---

license.txt

Update the copyright year in license.txt to 2007-2020

---

readme.txt

Add itpixelz to Contributors in readme.txt

---

readme.txt

Revise readme.txt based on the documentation style guide

---

readme.txt

Add 3.3 change log to readme.txt

---

bogo.php

Update Version and the BOGO_VERSION constant to 3.3 in bogo.php

---

admin/includes/js/admin.js
admin/includes/post.php
includes/functions.php

Improve the Language metabox for Classic Editor

---

includes/user.php

Improve bogo_admin_bar_menu()

---

includes/block-editor.php

Block Editor: Update the dependency array.

---

includes/post.php

Ensure all translation posts have the same _original_post

---

readme.txt

Update Requires at least (5.3), and Tested up to (5.3)

---

readme.txt

Add 3.3.1 change log to readme.txt

---

bogo.php

Update Version and the BOGO_VERSION constant to 3.3.1 in bogo.php

---

admin/admin.php

Avoid PHP notices

---

bogo.php

Remove unused conditional statements

---

admin/includes/user.php

Remove unnecessary function according to supported WordPress versions

---

package.json

Update the package.json file following webpack documentation

---

includes/functions.php

Use wp_parse_url() instead of parse_url()

---

admin/includes/post.php

Instead, only check if the user has a general ability to edit posts.
See #84

Not necessary to check if the user can edit the post

---

includes/rest-api.php

REST API: Ensure correct capability checks are applied

---

admin/admin.php
admin/includes/terms-translation.php
includes/capabilities.php

Allow to edit translation if the user has cap for the term

---

includes/capabilities.php

Ensure $accessible_locales can store multiple users

---

admin/admin.php
admin/includes/terms-translation.php

If $item['cap'] isn't set check the bogo_edit_terms_translation cap

---

includes/user.php

Not the locale set in the URL.
See #76

Let the admin bar locale follow the user locale

---

includes/functions.php
includes/user.php

Check if is_locale_switched()

---

includes/functions.php
includes/language-switcher.php

More "short name" option

---

includes/functions.php

Add Spanish (Puerto Rico)

---

admin/admin.php
admin/includes/language-packs.php
admin/includes/nav-menu.php
admin/includes/post.php
admin/includes/terms-translation.php
admin/includes/user.php
admin/includes/widgets.php
includes/functions.php
includes/language-switcher.php
includes/link-template.php
includes/rest-api.php
includes/user.php

Set exclude_enus_if_inactive to true by default

---

admin/admin.php

Set correct condition to access the Terms Translation page

---

bogo.php
readme.txt

Prepare for 3.3.2 release

---

bogo.php
includes/functions.php

Use determine_locale() instead of get_locale()

---

bogo.php

Recognize lang var even when is_admin()

---

includes/user.php

Switch locale just before rendering Tool Bar

---

bogo.php
readme.txt

Prepare for 3.3.3 release

---

bogo.php

Fix unintended locale selection in the Posts screen

---

admin/admin.php
admin/includes/terms-translation.php

Support set_screen_option_{$option} filter hook

---

includes/rest-api.php

Add permission_callback to REST API endpoints

---

bogo.php
readme.txt

Prepare for 3.3.4 release

---

admin/admin.php

Remove the set-screen-option filter

---

includes/post.php

Add auth_callback to post meta definition

---

includes/post.php

Suppress locale query during XML sitemap generation

---

includes/rewrite.php

Fix the creation of localized permalinks for taxonomies

---

includes/rewrite.php

Remove use of extract()

---

includes/rewrite.php

Refactor bogo_generate_rewrite_rules()

---

includes/rewrite.php

Move rewrite rules to rewrite_rules_array

---

includes/rewrite.php

Move root rules to rewrite_rules_array

---

includes/rewrite.php

`%lang%` must come after `$root`.
#152

Correct %lang% insertion

---

includes/rewrite.php

Move post rules to rewrite_rules_array

---

includes/rewrite.php

Move date rules to rewrite_rules_array

---

includes/rewrite.php

Introduce bogo_add_lang_to_permastruct()

---

includes/rewrite.php

Move comments, search, and author rules to rewrite_rules_array

---

includes/rewrite.php

Refactor bogo_rewrite_rules_array()

---

includes/rewrite.php

Suppress generating unused rewrite rules

---

bogo.php
license.txt
readme.txt

Prepare for 3.5 release

---

includes/rewrite.php

Revert #155

---

includes/functions.php

Generate correct URL with a lang query when using index permalinks

---

bogo.php

Get correct locale from URL using index permalink

---

includes/functions.php

Improve URL output when using index permalinks

---

includes/rewrite.php

Add rewrite rules for REST routes with index permalinks

---

includes/rewrite.php

Correct order of CPT rewrite rules

---

bogo.php
readme.txt

Prepare for 3.5.1 release

---

includes/functions.php

Use assertion to avoid lang slug pattern matching part of word

---

bogo.php
readme.txt

Prepare for 3.5.2 release

---

admin/admin.php
includes/block-editor/block-editor.php

Don't enqueue bogo-block-editor in non-post screens

---

bogo.php
readme.txt

Prepare for 3.5.3 release

---

includes/post.php

Avoid multiple serialization

---

admin/includes/js/admin.js

Fix jQuery for the Site Language switcher

---

includes/block-editor/block-editor.php
includes/block-editor/language-switcher/block.json
includes/block-editor/language-switcher/index.js
includes/block-editor/language-switcher/src/index.js

Set up language switcher block

---

.gitignore
includes/block-editor/language-switcher/index.asset.php

Add language-switcher/index.asset.php

---

admin/admin.php

Use short name when available

---

bogo.php
readme.txt

Prepare for 3.6 release

---

bogo.php
license.txt
readme.txt

Prepare for 3.6.1 release

---

bogo.php

Update plugin header

---

bogo.php
includes/language-switcher.php
includes/shortcodes.php

Move shortcodes functions to shortcodes.php

---

admin/includes/terms-translation.php

Use bogo_format_atts() in terms translation

---

admin/includes/terms-translation.php

Hide Tagline when the original is empty

---

includes/language-functions.php

Add bogo_get_language filter hook

---

includes/language-functions.php

Add bogo_get_language_native_name filter hook

---

includes/language-functions.php

Add bogo_get_country_code filter hook

---

includes/css/style.css

Revert .bogoflags-before:before selector

---

includes/css/style.css

Add comment for devs

---

includes/block-editor/language-switcher/block.json

Update apiVersion to 3

---

includes/language-functions.php

bogo_http_accept_languages() always returns array

---

admin/admin.php
admin/includes/language-packs.php
admin/includes/post.php
admin/includes/terms-translation.php
includes/user.php

Use null coalescing operator

---

admin/includes/language-packs.php

Remove .l10n.php files

---

bogo.php
readme.txt

Prepare for 3.8.2 release

---

admin/admin.php

Coding standards

---

admin/admin.php
admin/includes/widgets.php
includes/flags.php

Use wp_kses_data()
